# Generated by Django 6.0.2 on 2026-06-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='role',
            field=models.CharField(choices=[('driver', 'Водитель'), ('passenger', 'Пассажир')], default='passenger', max_length=20),
        ),
    ]
