# Generated by Django 6.0.2 on 2026-06-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customeruser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='О себе'),
        ),
    ]
