# Generated by Django 6.0.2 on 2026-06-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customeruser_phone_number_customeruser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
