# Generated by Django 6.0.2 on 2026-06-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trip_free_seats_trip_total_seats_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_date',
            field=models.DateTimeField(),
        ),
    ]
