# Generated by Django 6.0.2 on 2026-06-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trip_comment_trip_is_completed_trip_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='is_completed',
            new_name='is_finished',
        ),
    ]
