# Generated by Django 6.0.2 on 2026-06-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_booking_unique_together_remove_trip_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_date',
            field=models.DateField(),
        ),
    ]
