# Generated by Django 6.0.2 on 2026-06-24 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trip_trip_time_alter_trip_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
